name: Final
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Go tests
      run: |
        go test ./... -v
      
    - name: Get short commit hash
      id: get_hash
      run: echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
    - name: Get commit message
      id: get_message
      run: echo "message=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: all
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push multi-arch image
      run: |
        docker buildx build \
          --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x \
          --build-arg CREATED=$(date --iso-8601=s) \
          --build-arg REVISION=${{ env.hash }} \
          -t sbnarra/terraform-http-backend:${{ env.hash }} \
          -t sbnarra/terraform-http-backend:latest \
          --output type=local,dest=./build \
          --push .

        mkdir -p dist
        find build -name terraform-http-backend | while read file; do
          cp "$file" "dist/$(echo "$file" | sed 's|build/linux_\([^/]*\)/terraform-http-backend|terraform-http-backend_\1|')"
        done

      # publish release with binaries
    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: dist/*
        tag: ${{ env.hash }}
        name: Release ${{ env.hash }}
        body: |
          Commit: ${{ env.hash }}
          Message: ${{ env.message }}
